// Sealed acceptance test for milestone 2. Do not edit this file.
//
// What the implementer must create
// --------------------------------
// `src/store/items.ts`, `src/store/users.ts`, and `src/store/annotations.ts`,
// with the exact API in `plan/briefs/02-store-spec.md`.
//
// Contract details this file pins down
// ------------------------------------
// The brief leaves these open. This file settles them, so build them this way.
//
// - Every insert returns the row it wrote, field for field, as the caller
//   passed it. The store adds nothing and rewrites nothing.
// - A UNIQUE failure of any kind throws `STORE_CONFLICT`, a duplicate primary
//   key included. Every other constraint failure, such as the CHECK on
//   `items.kind` or on `annotations.end_offset`, throws
//   `STORE_CONSTRAINT_FAILED`. No raw `SQLiteError` leaves L2.
// - `updateItem` changes only the fields the caller names. A field left out
//   keeps its stored value. `author: null` clears the author.
// - `updateAnnotation` writes `updated_at` from the `now` argument and never
//   touches `created_at`. It writes only the fields the caller names.
// - Every function in `users.ts` except `getUser`, `getUserBySubject`, and
//   `getApiTokenByHash` filters on `user_id`, `touchApiToken` included.
// - A tenant-scoped delete that matches nothing is silent, and a
//   cross-tenant delete is one of those cases: it removes nothing and throws
//   nothing.
//
// Tenancy
// -------
// Every tenant-scoped function is tested with two users who each own a row.
// A function that forgets its `user_id` filter fails here.
//
// Identifiers
// -----------
// Every id is a lowercase UUID, because `src/store/files.ts` accepts nothing
// else and the same ids travel to disk. The helpers below mint ids whose
// lexical order matches their number, so ordering tests read plainly.
//
// Timestamps
// ----------
// Every timestamp is a literal the test controls. A store that reads the
// clock fails these tests.

import { describe, expect, test } from "bun:test";
import { Database } from "bun:sqlite";

import type {
  Annotation,
  ApiToken,
  Item,
  ItemKind,
  User,
} from "../../src/contracts/item";
import { AppError, isAppError } from "../../src/contracts/errors";
import { migrate } from "../../src/store/db";
import {
  deleteItem,
  getItem,
  getItemByUrl,
  insertItem,
  listItems,
  markIngested,
  updateItem,
} from "../../src/store/items";
import {
  deleteApiToken,
  getApiTokenByHash,
  getUser,
  getUserBySubject,
  insertApiToken,
  insertUser,
  listApiTokens,
  touchApiToken,
} from "../../src/store/users";
import {
  deleteAnnotation,
  getAnnotation,
  insertAnnotation,
  listAnnotations,
  updateAnnotation,
} from "../../src/store/annotations";

const T0 = new Date("2026-02-01T00:00:00.000Z");
const T1 = new Date("2026-02-02T00:00:00.000Z");
const T2 = new Date("2026-02-03T00:00:00.000Z");

const ALICE = "11111111-1111-4111-8111-111111111111";
const BOB = "22222222-2222-4222-8222-222222222222";

function itemId(n: number): string {
  return `aaaaaaaa-0000-4000-8000-${String(n).padStart(12, "0")}`;
}

function annotationId(n: number): string {
  return `bbbbbbbb-0000-4000-8000-${String(n).padStart(12, "0")}`;
}

function tokenId(n: number): string {
  return `dddddddd-0000-4000-8000-${String(n).padStart(12, "0")}`;
}

function freshDb(): Database {
  const db = new Database(":memory:");
  db.exec("PRAGMA foreign_keys = ON");
  migrate(db, T0);
  return db;
}

function caught(run: () => unknown): unknown {
  try {
    run();
  } catch (error) {
    return error;
  }
  throw new Error("expected the call to throw");
}

function appErrorCode(error: unknown): string {
  expect(isAppError(error)).toBe(true);
  return (error as AppError).code;
}

function makeUser(id: string, subject: string): User {
  return {
    id,
    subject,
    email: `${subject}@example.com`,
    created_at: T0.toISOString(),
  };
}

function makeItem(overrides: Partial<Item> & { id: string; user_id: string }): Item {
  return {
    kind: "article",
    url: `https://example.com/${overrides.id}`,
    title: "A title",
    author: null,
    created_at: T0.toISOString(),
    ingested_at: null,
    ...overrides,
  };
}

function makeAnnotation(
  overrides: Partial<Annotation> & { id: string; user_id: string; item_id: string },
): Annotation {
  return {
    start_offset: 0,
    end_offset: 4,
    quote: "quot",
    note: null,
    created_at: T0.toISOString(),
    updated_at: T0.toISOString(),
    ...overrides,
  };
}

function makeToken(overrides: Partial<ApiToken> & { id: string; user_id: string }): ApiToken {
  return {
    name: "laptop",
    token_hash: `hash-${overrides.id}`,
    created_at: T0.toISOString(),
    last_used_at: null,
    ...overrides,
  };
}

function twoUsers(db: Database): void {
  insertUser(db, makeUser(ALICE, "alice"));
  insertUser(db, makeUser(BOB, "bob"));
}

function countRows(db: Database, table: string): number {
  return db.query<{ n: number }, []>(`SELECT COUNT(*) AS n FROM ${table}`).get()!.n;
}

describe("src/store/users", () => {
  test("insertUser returns the row and getUser reads it back", () => {
    const db = freshDb();
    const user = makeUser(ALICE, "alice");
    expect(insertUser(db, user)).toEqual(user);
    expect(getUser(db, ALICE)).toEqual(user);
    db.close();
  });

  test("getUser returns null for an unknown id", () => {
    const db = freshDb();
    insertUser(db, makeUser(ALICE, "alice"));
    expect(getUser(db, BOB)).toBeNull();
    db.close();
  });

  test("getUserBySubject finds the right user and null for the rest", () => {
    const db = freshDb();
    twoUsers(db);
    expect(getUserBySubject(db, "bob")?.id).toBe(BOB);
    expect(getUserBySubject(db, "alice")?.id).toBe(ALICE);
    expect(getUserBySubject(db, "carol")).toBeNull();
    db.close();
  });

  test("a null email round-trips as null", () => {
    const db = freshDb();
    const user: User = { ...makeUser(ALICE, "alice"), email: null };
    insertUser(db, user);
    expect(getUser(db, ALICE)!.email).toBeNull();
    db.close();
  });

  test("a duplicate subject throws STORE_CONFLICT", () => {
    const db = freshDb();
    insertUser(db, makeUser(ALICE, "alice"));
    const error = caught(() => insertUser(db, makeUser(BOB, "alice")));
    expect(appErrorCode(error)).toBe("STORE_CONFLICT");
    expect(countRows(db, "users")).toBe(1);
    db.close();
  });

  test("a duplicate id throws STORE_CONFLICT", () => {
    const db = freshDb();
    insertUser(db, makeUser(ALICE, "alice"));
    const error = caught(() => insertUser(db, makeUser(ALICE, "second")));
    expect(appErrorCode(error)).toBe("STORE_CONFLICT");
    expect(countRows(db, "users")).toBe(1);
    db.close();
  });
});

describe("src/store/users api tokens", () => {
  test("insertApiToken returns the row and getApiTokenByHash reads it back", () => {
    const db = freshDb();
    twoUsers(db);
    const token = makeToken({ id: tokenId(1), user_id: ALICE });
    expect(insertApiToken(db, token)).toEqual(token);
    expect(getApiTokenByHash(db, `hash-${tokenId(1)}`)).toEqual(token);
    expect(getApiTokenByHash(db, "hash-missing")).toBeNull();
    db.close();
  });

  test("a duplicate token_hash throws STORE_CONFLICT", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(1), user_id: ALICE }));
    const error = caught(() =>
      insertApiToken(
        db,
        makeToken({
          id: tokenId(2),
          user_id: BOB,
          token_hash: `hash-${tokenId(1)}`,
        }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_CONFLICT");
    expect(countRows(db, "api_tokens")).toBe(1);
    db.close();
  });

  test("listApiTokens returns only the caller's tokens", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(1), user_id: ALICE }));
    insertApiToken(db, makeToken({ id: tokenId(2), user_id: ALICE, name: "phone" }));
    insertApiToken(db, makeToken({ id: tokenId(3), user_id: BOB }));

    const forAlice = listApiTokens(db, ALICE);
    expect(forAlice).toHaveLength(2);
    expect(forAlice.map((token) => token.id).toSorted()).toEqual([
      tokenId(1),
      tokenId(2),
    ]);
    for (const token of forAlice) {
      expect(token.user_id).toBe(ALICE);
    }

    const forBob = listApiTokens(db, BOB);
    expect(forBob).toHaveLength(1);
    expect(forBob[0]!.id).toBe(tokenId(3));
    db.close();
  });

  test("listApiTokens returns an empty array for a user with none", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(1), user_id: ALICE }));
    expect(listApiTokens(db, BOB)).toEqual([]);
    db.close();
  });

  test("touchApiToken writes last_used_at from the caller's clock", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(1), user_id: ALICE }));
    expect(getApiTokenByHash(db, `hash-${tokenId(1)}`)!.last_used_at).toBeNull();

    touchApiToken(db, ALICE, tokenId(1), T2);
    expect(getApiTokenByHash(db, `hash-${tokenId(1)}`)!.last_used_at).toBe(
      "2026-02-03T00:00:00.000Z",
    );
    db.close();
  });

  test("touchApiToken cannot touch another user's token", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(3), user_id: BOB }));

    touchApiToken(db, ALICE, tokenId(3), T2);

    expect(getApiTokenByHash(db, `hash-${tokenId(3)}`)!.last_used_at).toBeNull();
    db.close();
  });

  test("touchApiToken on an unknown id changes nothing", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(1), user_id: ALICE }));
    touchApiToken(db, ALICE, tokenId(9), T2);
    expect(getApiTokenByHash(db, `hash-${tokenId(1)}`)!.last_used_at).toBeNull();
    db.close();
  });

  test("deleteApiToken removes the caller's own token", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(1), user_id: ALICE }));
    deleteApiToken(db, ALICE, tokenId(1));
    expect(getApiTokenByHash(db, `hash-${tokenId(1)}`)).toBeNull();
    expect(listApiTokens(db, ALICE)).toEqual([]);
    db.close();
  });

  test("deleteApiToken cannot delete another user's token", () => {
    const db = freshDb();
    twoUsers(db);
    insertApiToken(db, makeToken({ id: tokenId(3), user_id: BOB }));

    deleteApiToken(db, ALICE, tokenId(3));

    expect(getApiTokenByHash(db, `hash-${tokenId(3)}`)).not.toBeNull();
    expect(listApiTokens(db, BOB)).toHaveLength(1);
    db.close();
  });

  test("deleteApiToken is silent for an unknown id", () => {
    const db = freshDb();
    twoUsers(db);
    expect(() => deleteApiToken(db, ALICE, tokenId(9))).not.toThrow();
    db.close();
  });
});

describe("src/store/items", () => {
  test("insertItem returns the row and getItem reads it back", () => {
    const db = freshDb();
    twoUsers(db);
    const item = makeItem({
      id: itemId(1),
      user_id: ALICE,
      author: "An author",
      ingested_at: T1.toISOString(),
    });
    expect(insertItem(db, item)).toEqual(item);
    expect(getItem(db, ALICE, itemId(1))).toEqual(item);
    db.close();
  });

  test("a book with no url round-trips", () => {
    const db = freshDb();
    twoUsers(db);
    const item = makeItem({
      id: itemId(1),
      user_id: ALICE,
      kind: "book",
      url: null,
      title: "A book",
    });
    insertItem(db, item);
    expect(getItem(db, ALICE, itemId(1))).toEqual(item);
    db.close();
  });

  test("getItem returns null for another user's item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(3), user_id: BOB }));

    expect(getItem(db, ALICE, itemId(3))).toBeNull();
    expect(getItem(db, BOB, itemId(3))).not.toBeNull();
    db.close();
  });

  test("getItem returns null for an unknown id", () => {
    const db = freshDb();
    twoUsers(db);
    expect(getItem(db, ALICE, itemId(9))).toBeNull();
    db.close();
  });

  test("a kind outside article and book throws STORE_CONSTRAINT_FAILED", () => {
    const db = freshDb();
    twoUsers(db);
    const error = caught(() =>
      insertItem(
        db,
        makeItem({ id: itemId(1), user_id: ALICE, kind: "video" as ItemKind }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_CONSTRAINT_FAILED");
    expect(countRows(db, "items")).toBe(0);
    db.close();
  });

  test("a second item with the same url throws STORE_CONFLICT", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(
      db,
      makeItem({ id: itemId(1), user_id: ALICE, url: "https://example.com/a" }),
    );

    const error = caught(() =>
      insertItem(
        db,
        makeItem({ id: itemId(2), user_id: ALICE, url: "https://example.com/a" }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_CONFLICT");
    expect(countRows(db, "items")).toBe(1);
    db.close();
  });

  test("two users may hold the same url", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(
      db,
      makeItem({ id: itemId(1), user_id: ALICE, url: "https://example.com/a" }),
    );
    insertItem(
      db,
      makeItem({ id: itemId(2), user_id: BOB, url: "https://example.com/a" }),
    );
    expect(countRows(db, "items")).toBe(2);
    db.close();
  });

  test("a null url never collides, so books stack up", () => {
    const db = freshDb();
    twoUsers(db);
    for (const n of [1, 2, 3]) {
      insertItem(
        db,
        makeItem({ id: itemId(n), user_id: ALICE, kind: "book", url: null }),
      );
    }
    expect(countRows(db, "items")).toBe(3);
    db.close();
  });

  test("getItemByUrl finds the caller's item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(
      db,
      makeItem({ id: itemId(1), user_id: ALICE, url: "https://example.com/a" }),
    );

    expect(getItemByUrl(db, ALICE, "https://example.com/a")?.id).toBe(itemId(1));
    expect(getItemByUrl(db, ALICE, "https://example.com/b")).toBeNull();
    db.close();
  });

  test("getItemByUrl never returns another user's item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(
      db,
      makeItem({ id: itemId(3), user_id: BOB, url: "https://example.com/a" }),
    );

    expect(getItemByUrl(db, ALICE, "https://example.com/a")).toBeNull();
    expect(getItemByUrl(db, BOB, "https://example.com/a")?.id).toBe(itemId(3));
    db.close();
  });

  test("listItems returns the caller's items, newest first", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(
      db,
      makeItem({ id: itemId(1), user_id: ALICE, created_at: "2026-02-01T00:00:00.000Z" }),
    );
    insertItem(
      db,
      makeItem({ id: itemId(2), user_id: ALICE, created_at: "2026-02-03T00:00:00.000Z" }),
    );
    insertItem(
      db,
      makeItem({ id: itemId(3), user_id: ALICE, created_at: "2026-02-02T00:00:00.000Z" }),
    );
    insertItem(
      db,
      makeItem({ id: itemId(4), user_id: BOB, created_at: "2026-02-04T00:00:00.000Z" }),
    );

    const rows = listItems(db, ALICE, 10);
    expect(rows.map((row) => row.id)).toEqual([itemId(2), itemId(3), itemId(1)]);
    db.close();
  });

  test("listItems breaks a created_at tie by id, descending", () => {
    const db = freshDb();
    twoUsers(db);
    const sameTime = "2026-02-05T00:00:00.000Z";
    for (const n of [1, 3, 2]) {
      insertItem(db, makeItem({ id: itemId(n), user_id: ALICE, created_at: sameTime }));
    }
    expect(listItems(db, ALICE, 10).map((row) => row.id)).toEqual([
      itemId(3),
      itemId(2),
      itemId(1),
    ]);
    db.close();
  });

  test("listItems honours the limit", () => {
    const db = freshDb();
    twoUsers(db);
    for (const n of [1, 2, 3, 4]) {
      insertItem(
        db,
        makeItem({
          id: itemId(n),
          user_id: ALICE,
          created_at: `2026-02-0${n}T00:00:00.000Z`,
        }),
      );
    }
    const rows = listItems(db, ALICE, 2);
    expect(rows.map((row) => row.id)).toEqual([itemId(4), itemId(3)]);
    db.close();
  });

  test("listItems with a cursor returns rows strictly after it in sort order", () => {
    const db = freshDb();
    twoUsers(db);
    for (const n of [1, 2, 3]) {
      insertItem(
        db,
        makeItem({
          id: itemId(n),
          user_id: ALICE,
          created_at: `2026-02-0${n}T00:00:00.000Z`,
        }),
      );
    }

    const rows = listItems(db, ALICE, 10, {
      created_at: "2026-02-02T00:00:00.000Z",
      id: itemId(2),
    });
    expect(rows.map((row) => row.id)).toEqual([itemId(1)]);

    const all = listItems(db, ALICE, 10, {
      created_at: "2026-02-04T00:00:00.000Z",
      id: itemId(9),
    });
    expect(all.map((row) => row.id)).toEqual([itemId(3), itemId(2), itemId(1)]);

    expect(
      listItems(db, ALICE, 10, {
        created_at: "2026-02-01T00:00:00.000Z",
        id: itemId(1),
      }),
    ).toEqual([]);
    db.close();
  });

  test("paging over items that share a timestamp skips nothing and repeats nothing", () => {
    // Two items written in the same millisecond. A cursor of created_at alone
    // either drops one or serves it forever, so the cursor carries the id too.
    const db = freshDb();
    twoUsers(db);
    const sameTime = "2026-02-05T00:00:00.000Z";
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE, created_at: sameTime }));
    insertItem(db, makeItem({ id: itemId(2), user_id: ALICE, created_at: sameTime }));

    const first = listItems(db, ALICE, 1);
    expect(first.map((row) => row.id)).toEqual([itemId(2)]);

    const second = listItems(db, ALICE, 1, {
      created_at: first[0]!.created_at,
      id: first[0]!.id,
    });
    expect(second.map((row) => row.id)).toEqual([itemId(1)]);

    const third = listItems(db, ALICE, 1, {
      created_at: second[0]!.created_at,
      id: second[0]!.id,
    });
    expect(third).toEqual([]);
    db.close();
  });

  test("listItems returns an empty array for a user with no items", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE }));
    expect(listItems(db, BOB, 10)).toEqual([]);
    db.close();
  });

  test("updateItem changes only the named fields and returns the new row", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(
      db,
      makeItem({ id: itemId(1), user_id: ALICE, title: "Old", author: "Old author" }),
    );

    const titled = updateItem(db, ALICE, itemId(1), { title: "New" });
    expect(titled.title).toBe("New");
    expect(titled.author).toBe("Old author");
    expect(titled.created_at).toBe(T0.toISOString());

    const authored = updateItem(db, ALICE, itemId(1), { author: "New author" });
    expect(authored.title).toBe("New");
    expect(authored.author).toBe("New author");

    expect(getItem(db, ALICE, itemId(1))).toEqual(authored);
    db.close();
  });

  test("updateItem clears the author when the caller passes null", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE, author: "An author" }));
    expect(updateItem(db, ALICE, itemId(1), { author: null }).author).toBeNull();
    expect(getItem(db, ALICE, itemId(1))!.author).toBeNull();
    db.close();
  });

  test("updateItem throws STORE_NOT_FOUND for another user's item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(3), user_id: BOB, title: "Bob's" }));

    const error = caught(() => updateItem(db, ALICE, itemId(3), { title: "Stolen" }));
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    expect(getItem(db, BOB, itemId(3))!.title).toBe("Bob's");
    db.close();
  });

  test("updateItem throws STORE_NOT_FOUND for an unknown id", () => {
    const db = freshDb();
    twoUsers(db);
    const error = caught(() => updateItem(db, ALICE, itemId(9), { title: "x" }));
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    db.close();
  });

  test("markIngested writes ingested_at from the caller's clock", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE }));

    const marked = markIngested(db, ALICE, itemId(1), T2);
    expect(marked.ingested_at).toBe("2026-02-03T00:00:00.000Z");
    expect(marked.created_at).toBe(T0.toISOString());
    expect(getItem(db, ALICE, itemId(1))!.ingested_at).toBe(
      "2026-02-03T00:00:00.000Z",
    );
    db.close();
  });

  test("markIngested throws STORE_NOT_FOUND for another user's item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(3), user_id: BOB }));

    const error = caught(() => markIngested(db, ALICE, itemId(3), T2));
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    expect(getItem(db, BOB, itemId(3))!.ingested_at).toBeNull();
    db.close();
  });

  test("deleteItem removes the caller's own item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE }));
    deleteItem(db, ALICE, itemId(1));
    expect(getItem(db, ALICE, itemId(1))).toBeNull();
    db.close();
  });

  test("deleteItem cannot delete another user's item", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(3), user_id: BOB }));

    expect(() => deleteItem(db, ALICE, itemId(3))).not.toThrow();

    expect(getItem(db, BOB, itemId(3))).not.toBeNull();
    expect(countRows(db, "items")).toBe(1);
    db.close();
  });

  test("deleteItem is silent for an unknown id", () => {
    const db = freshDb();
    twoUsers(db);
    expect(() => deleteItem(db, ALICE, itemId(9))).not.toThrow();
    db.close();
  });

  test("deleting an item cascades to its annotations", () => {
    const db = freshDb();
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE }));
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(1), user_id: ALICE, item_id: itemId(1) }),
    );
    expect(countRows(db, "annotations")).toBe(1);

    deleteItem(db, ALICE, itemId(1));
    expect(countRows(db, "annotations")).toBe(0);
    db.close();
  });
});

describe("src/store/annotations", () => {
  function seed(db: Database): void {
    twoUsers(db);
    insertItem(db, makeItem({ id: itemId(1), user_id: ALICE }));
    insertItem(db, makeItem({ id: itemId(2), user_id: ALICE }));
    insertItem(db, makeItem({ id: itemId(3), user_id: BOB }));
  }

  test("insertAnnotation returns the row and getAnnotation reads it back", () => {
    const db = freshDb();
    seed(db);
    const annotation = makeAnnotation({
      id: annotationId(1),
      user_id: ALICE,
      item_id: itemId(1),
      start_offset: 10,
      end_offset: 24,
      quote: "a quoted span",
      note: "a note",
    });
    expect(insertAnnotation(db, annotation)).toEqual(annotation);
    expect(getAnnotation(db, ALICE, annotationId(1))).toEqual(annotation);
    db.close();
  });

  test("getAnnotation returns null for another user's annotation", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(3), user_id: BOB, item_id: itemId(3) }),
    );

    expect(getAnnotation(db, ALICE, annotationId(3))).toBeNull();
    expect(getAnnotation(db, BOB, annotationId(3))).not.toBeNull();
    db.close();
  });

  test("insertAnnotation throws STORE_NOT_FOUND for another user's item", () => {
    const db = freshDb();
    seed(db);
    const error = caught(() =>
      insertAnnotation(
        db,
        makeAnnotation({ id: annotationId(9), user_id: ALICE, item_id: itemId(3) }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    expect(countRows(db, "annotations")).toBe(0);
    db.close();
  });

  test("insertAnnotation throws STORE_NOT_FOUND for an unknown item", () => {
    const db = freshDb();
    seed(db);
    const error = caught(() =>
      insertAnnotation(
        db,
        makeAnnotation({ id: annotationId(9), user_id: ALICE, item_id: itemId(8) }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    expect(countRows(db, "annotations")).toBe(0);
    db.close();
  });

  test("an end before the start throws STORE_CONSTRAINT_FAILED", () => {
    const db = freshDb();
    seed(db);
    const error = caught(() =>
      insertAnnotation(
        db,
        makeAnnotation({
          id: annotationId(1),
          user_id: ALICE,
          item_id: itemId(1),
          start_offset: 20,
          end_offset: 10,
        }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_CONSTRAINT_FAILED");
    expect(countRows(db, "annotations")).toBe(0);
    db.close();
  });

  test("a negative start offset throws STORE_CONSTRAINT_FAILED", () => {
    const db = freshDb();
    seed(db);
    const error = caught(() =>
      insertAnnotation(
        db,
        makeAnnotation({
          id: annotationId(1),
          user_id: ALICE,
          item_id: itemId(1),
          start_offset: -1,
          end_offset: 4,
        }),
      ),
    );
    expect(appErrorCode(error)).toBe("STORE_CONSTRAINT_FAILED");
    expect(countRows(db, "annotations")).toBe(0);
    db.close();
  });

  test("listAnnotations orders by start_offset then id", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(3),
        user_id: ALICE,
        item_id: itemId(1),
        start_offset: 30,
        end_offset: 40,
      }),
    );
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(2),
        user_id: ALICE,
        item_id: itemId(1),
        start_offset: 10,
        end_offset: 20,
      }),
    );
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(1),
        user_id: ALICE,
        item_id: itemId(1),
        start_offset: 10,
        end_offset: 15,
      }),
    );

    expect(listAnnotations(db, ALICE, itemId(1)).map((row) => row.id)).toEqual([
      annotationId(1),
      annotationId(2),
      annotationId(3),
    ]);
    db.close();
  });

  test("listAnnotations returns only the named item", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(1), user_id: ALICE, item_id: itemId(1) }),
    );
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(2), user_id: ALICE, item_id: itemId(2) }),
    );

    const rows = listAnnotations(db, ALICE, itemId(1));
    expect(rows).toHaveLength(1);
    expect(rows[0]!.id).toBe(annotationId(1));
    db.close();
  });

  test("listAnnotations never returns another user's annotations", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(3), user_id: BOB, item_id: itemId(3) }),
    );

    expect(listAnnotations(db, ALICE, itemId(3))).toEqual([]);
    expect(listAnnotations(db, BOB, itemId(3))).toHaveLength(1);
    db.close();
  });

  test("updateAnnotation writes the note and updated_at, keeping created_at", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(1), user_id: ALICE, item_id: itemId(1) }),
    );

    const updated = updateAnnotation(
      db,
      ALICE,
      annotationId(1),
      { note: "a note" },
      T2,
    );
    expect(updated.note).toBe("a note");
    expect(updated.created_at).toBe(T0.toISOString());
    expect(updated.updated_at).toBe("2026-02-03T00:00:00.000Z");
    expect(getAnnotation(db, ALICE, annotationId(1))).toEqual(updated);
    db.close();
  });

  test("updateAnnotation clears the note when the caller passes null", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(1),
        user_id: ALICE,
        item_id: itemId(1),
        note: "a note",
      }),
    );

    const cleared = updateAnnotation(db, ALICE, annotationId(1), { note: null }, T1);
    expect(cleared.note).toBeNull();
    expect(cleared.updated_at).toBe("2026-02-02T00:00:00.000Z");
    db.close();
  });

  test("updateAnnotation rewrites the offsets and the quote", () => {
    // Re-anchoring returns repaired offsets and a repaired quote, and this is
    // the only function that persists them.
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(1),
        user_id: ALICE,
        item_id: itemId(1),
        start_offset: 10,
        end_offset: 20,
        quote: "old quote",
        note: "a note",
      }),
    );

    const moved = updateAnnotation(
      db,
      ALICE,
      annotationId(1),
      { start_offset: 30, end_offset: 45, quote: "new quote" },
      T2,
    );
    expect(moved.start_offset).toBe(30);
    expect(moved.end_offset).toBe(45);
    expect(moved.quote).toBe("new quote");
    expect(moved.note).toBe("a note");
    expect(moved.updated_at).toBe("2026-02-03T00:00:00.000Z");
    expect(getAnnotation(db, ALICE, annotationId(1))).toEqual(moved);
    db.close();
  });

  test("updateAnnotation with an end before the start throws STORE_CONSTRAINT_FAILED", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(1),
        user_id: ALICE,
        item_id: itemId(1),
        start_offset: 10,
        end_offset: 20,
      }),
    );

    const error = caught(() =>
      updateAnnotation(db, ALICE, annotationId(1), { end_offset: 5 }, T2),
    );
    expect(appErrorCode(error)).toBe("STORE_CONSTRAINT_FAILED");

    const stored = getAnnotation(db, ALICE, annotationId(1))!;
    expect(stored.end_offset).toBe(20);
    expect(stored.updated_at).toBe(T0.toISOString());
    db.close();
  });

  test("updateAnnotation throws STORE_NOT_FOUND for another user's annotation", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({
        id: annotationId(3),
        user_id: BOB,
        item_id: itemId(3),
        note: "Bob's note",
      }),
    );

    const error = caught(() =>
      updateAnnotation(db, ALICE, annotationId(3), { note: "stolen" }, T2),
    );
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    expect(getAnnotation(db, BOB, annotationId(3))!.note).toBe("Bob's note");
    db.close();
  });

  test("updateAnnotation throws STORE_NOT_FOUND for an unknown id", () => {
    const db = freshDb();
    seed(db);
    const error = caught(() =>
      updateAnnotation(db, ALICE, annotationId(9), { note: "x" }, T2),
    );
    expect(appErrorCode(error)).toBe("STORE_NOT_FOUND");
    db.close();
  });

  test("deleteAnnotation removes the caller's own annotation", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(1), user_id: ALICE, item_id: itemId(1) }),
    );
    deleteAnnotation(db, ALICE, annotationId(1));
    expect(getAnnotation(db, ALICE, annotationId(1))).toBeNull();
    expect(countRows(db, "annotations")).toBe(0);
    db.close();
  });

  test("deleteAnnotation cannot delete another user's annotation", () => {
    const db = freshDb();
    seed(db);
    insertAnnotation(
      db,
      makeAnnotation({ id: annotationId(3), user_id: BOB, item_id: itemId(3) }),
    );

    expect(() => deleteAnnotation(db, ALICE, annotationId(3))).not.toThrow();

    expect(getAnnotation(db, BOB, annotationId(3))).not.toBeNull();
    expect(countRows(db, "annotations")).toBe(1);
    db.close();
  });

  test("deleteAnnotation is silent for an unknown id", () => {
    const db = freshDb();
    seed(db);
    expect(() => deleteAnnotation(db, ALICE, annotationId(9))).not.toThrow();
    db.close();
  });
});
