// Sealed acceptance test for milestone 2. Do not edit this file.
//
// What the implementer must create
// --------------------------------
// 1. `src/store/db.ts`, with the exact API in `plan/briefs/02-store-spec.md`.
// 2. The six new codes in `src/contracts/errors.ts`.
// 3. Three exports in `test/invariants/lib.ts`:
//
//      export type SchemaViolation = { table: string; rule: string; detail: string };
//      export const EXPECTED_COLUMNS: Record<string, readonly string[]>;
//      export function checkTenancy(tables: TableInfo[]): SchemaViolation[];
//      export function checkNoPositionsInDb(tables: TableInfo[]): SchemaViolation[];
//
//    `TableInfo` comes from `src/store/db.ts`. `SchemaViolation` is a new type;
//    the existing `Violation` carries `file` and `line`, which mean nothing for
//    a table, so do not reuse it.
// 4. `test/invariants/tenancy.test.ts` and
//    `test/invariants/no-positions-in-db.test.ts`, which run those checkers
//    over the real schema. This file proves the checkers work; those files
//    wire them into the gate.
//
// Contract details this file pins down
// ------------------------------------
// The brief leaves these open. This file settles them, so build them this way.
//
// - `EXPECTED_COLUMNS` is the one place the column set of each table lives.
//   Its keys are the seven tables of version 1. Each value is that table's
//   column names, sorted. The tests below pin the values literally, then
//   compare the migrated database against the same constant, so a schema
//   change has exactly one place to land.
// - `checkNoPositionsInDb` exempts the same tables `checkTenancy` exempts for
//   SQLite's own use: any table named with the `sqlite_` prefix, and the five
//   shadow tables of each FTS5 virtual table. `migrations` and `users` are not
//   exempt here, because both appear in `EXPECTED_COLUMNS`.
// - A table with no entry in `EXPECTED_COLUMNS` is not failed by the allowlist
//   pass. Its columns still run through the name pass, which is what covers a
//   table a later milestone adds.
// - `migrate` returns the count of versions it applied. On a fresh database
//   that is `MIGRATIONS.length`. On an already-migrated database it is 0.
// - `migrate` does not assume the `migrations` table exists. Version 1's SQL
//   creates it, so `migrate` must read the applied versions in a way that
//   tolerates a database with no tables at all.
// - A migration that fails part way leaves nothing behind: no `migrations`
//   row, and none of the tables that version created.
// - `tableInfo` lists every `sqlite_master` row of type `table`. That includes
//   the shadow tables SQLite creates for `items_fts`. The checkers, not
//   `tableInfo`, are what exempt them.
// - The `applied_at` value of a migration row is exactly `now.toISOString()`.
//   The store never reads the clock.
// - `openDatabase` migrates before it returns.
//
// Timestamps
// ----------
// Every timestamp in this file is a literal the test controls. A store that
// generates its own fails these tests.

import { afterAll, describe, expect, test } from "bun:test";
import { Database } from "bun:sqlite";
import { existsSync } from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { AppError, ERROR_CODES, isAppError } from "../../src/contracts/errors";
import type { TableInfo } from "../../src/store/db";
import {
  MIGRATIONS,
  SCHEMA_VERSION,
  migrate,
  openDatabase,
  tableInfo,
} from "../../src/store/db";
import type { SchemaViolation } from "../invariants/lib";
import {
  EXPECTED_COLUMNS,
  checkNoPositionsInDb,
  checkTenancy,
} from "../invariants/lib";

const APPLIED_AT = new Date("2026-02-01T00:00:00.000Z");

const SCHEMA_TABLES = [
  "annotations",
  "api_tokens",
  "fetch_requests",
  "items",
  "items_fts",
  "migrations",
  "users",
];

const FTS_SHADOW_SUFFIXES = ["_data", "_idx", "_content", "_docsize", "_config"];

const tempRoots: string[] = [];

async function tempDbPath(name: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "commonplace-store-schema-"));
  tempRoots.push(root);
  return join(root, name);
}

afterAll(async () => {
  for (const root of tempRoots) {
    await rm(root, { recursive: true, force: true });
  }
});

function caught(run: () => unknown): unknown {
  try {
    run();
  } catch (error) {
    return error;
  }
  throw new Error("expected the call to throw");
}

function appErrorCode(error: unknown): string {
  expect(isAppError(error)).toBe(true);
  return (error as AppError).code;
}

function migratedMemoryDb(): Database {
  const db = new Database(":memory:");
  db.exec("PRAGMA foreign_keys = ON");
  migrate(db, APPLIED_AT);
  return db;
}

function pragma(db: Database, name: string): unknown {
  const result = db.query<Record<string, unknown>, []>(`PRAGMA ${name}`).get();
  if (result === null) return null;
  return Object.values(result)[0];
}

function tableNames(db: Database): string[] {
  return db
    .query<{ name: string }, []>(
      "SELECT name FROM sqlite_master WHERE type = 'table'",
    )
    .all()
    .map((row) => row.name);
}

function columnsOf(tables: TableInfo[], name: string): string[] {
  const found = tables.find((table) => table.name === name);
  expect(found).toBeDefined();
  return [...found!.columns].toSorted();
}

function fakeTable(name: string, columns: string[], sql?: string): TableInfo {
  return {
    name,
    sql: sql ?? `CREATE TABLE ${name} (${columns.join(", ")})`,
    columns,
  };
}

function fakeFtsTable(name: string, columns: string[]): TableInfo {
  return {
    name,
    sql: `CREATE VIRTUAL TABLE ${name} USING fts5(${columns.join(", ")})`,
    columns,
  };
}

function fakeShadowTables(name: string): TableInfo[] {
  return FTS_SHADOW_SUFFIXES.map((suffix) =>
    fakeTable(`${name}${suffix}`, ["id", "block"]),
  );
}

function schemaTables(): TableInfo[] {
  return Object.entries(EXPECTED_COLUMNS).map(([name, columns]) =>
    name === "items_fts"
      ? fakeFtsTable(name, [...columns])
      : fakeTable(name, [...columns]),
  );
}

function detailOf(violations: SchemaViolation[]): string {
  return violations.map((violation) => `${violation.table} ${violation.detail}`).join(" ");
}

describe("src/contracts/errors ERROR_CODES", () => {
  test("holds the five store codes this milestone adds", () => {
    const codes = ERROR_CODES as readonly string[];
    expect(codes).toContain("STORE_MIGRATION_FAILED");
    expect(codes).toContain("STORE_NOT_FOUND");
    expect(codes).toContain("STORE_CONFLICT");
    expect(codes).toContain("STORE_INVALID_PATH");
    expect(codes).toContain("STORE_WRITE_FAILED");
    expect(codes).toContain("STORE_CONSTRAINT_FAILED");
  });

  test("holds STORE_BUSY, which claimNext throws on a write conflict", () => {
    expect(ERROR_CODES as readonly string[]).toContain("STORE_BUSY");
  });

  test("holds INGEST_ATTEMPTS_EXHAUSTED, which the sweep stores", () => {
    expect(ERROR_CODES as readonly string[]).toContain(
      "INGEST_ATTEMPTS_EXHAUSTED",
    );
  });

  test("keeps the codes earlier milestones added", () => {
    const codes = ERROR_CODES as readonly string[];
    expect(codes).toContain("CONFIG_FILE_MISSING");
    expect(codes).toContain("WALK_MAP_MALFORMED");
    expect(codes).toContain("ACQUIRE_TOOL_MISSING");
  });
});

describe("src/store/db MIGRATIONS", () => {
  test("SCHEMA_VERSION is 1", () => {
    expect(SCHEMA_VERSION).toBe(1);
  });

  test("holds one entry per version, ascending, ending at SCHEMA_VERSION", () => {
    expect(MIGRATIONS.length).toBeGreaterThan(0);
    const versions = MIGRATIONS.map((migration) => migration.version);
    expect(versions).toEqual([...versions].toSorted((a, b) => a - b));
    expect(new Set(versions).size).toBe(versions.length);
    expect(versions.at(-1)).toBe(SCHEMA_VERSION);
    expect(versions[0]).toBe(1);
  });

  test("every entry carries non-empty SQL", () => {
    for (const migration of MIGRATIONS) {
      expect(typeof migration.sql).toBe("string");
      expect(migration.sql.trim().length).toBeGreaterThan(0);
    }
  });

  test("version 1 creates the seven tables the brief lists", () => {
    const sql = MIGRATIONS[0]!.sql;
    for (const name of SCHEMA_TABLES) {
      expect(sql).toContain(name);
    }
    expect(sql).toContain("USING fts5");
  });
});

describe("src/store/db migrate", () => {
  test("applies every version on a fresh database and returns the count", () => {
    const db = new Database(":memory:");
    expect(migrate(db, APPLIED_AT)).toBe(MIGRATIONS.length);
    expect(tableNames(db)).toContain("items");
    db.close();
  });

  test("records each applied version with the caller's timestamp", () => {
    const db = migratedMemoryDb();
    const rows = db
      .query<{ version: number; applied_at: string }, []>(
        "SELECT version, applied_at FROM migrations ORDER BY version",
      )
      .all();
    expect(rows).toHaveLength(MIGRATIONS.length);
    expect(rows.map((row) => row.version)).toEqual(
      MIGRATIONS.map((migration) => migration.version),
    );
    for (const row of rows) {
      expect(row.applied_at).toBe("2026-02-01T00:00:00.000Z");
    }
    db.close();
  });

  test("a second call applies nothing and returns 0", () => {
    const db = migratedMemoryDb();
    const before = tableInfo(db).map((table) => table.name).toSorted();

    expect(migrate(db, new Date("2026-03-01T00:00:00.000Z"))).toBe(0);
    expect(migrate(db, new Date("2026-04-01T00:00:00.000Z"))).toBe(0);

    expect(tableInfo(db).map((table) => table.name).toSorted()).toEqual(before);
    const applied = db
      .query<{ applied_at: string }, []>(
        "SELECT applied_at FROM migrations WHERE version = 1",
      )
      .all();
    expect(applied).toHaveLength(1);
    expect(applied[0]!.applied_at).toBe("2026-02-01T00:00:00.000Z");
    db.close();
  });

  test("a failing migration throws STORE_MIGRATION_FAILED and rolls back", () => {
    // A hand-made `items` table collides with the one version 1 creates, so
    // version 1 fails part way through. Everything it created before the
    // collision must disappear with it.
    const db = new Database(":memory:");
    db.exec("CREATE TABLE items (id TEXT PRIMARY KEY, mine TEXT)");

    const error = caught(() => migrate(db, APPLIED_AT));
    expect(appErrorCode(error)).toBe("STORE_MIGRATION_FAILED");

    const names = tableNames(db);
    expect(names).toContain("items");
    expect(names).not.toContain("users");
    expect(names).not.toContain("annotations");
    expect(names).not.toContain("fetch_requests");

    // The hand-made table is untouched: the rollback dropped only what the
    // migration created.
    const columns = db
      .query<{ name: string }, []>("PRAGMA table_info(items)")
      .all()
      .map((row) => row.name)
      .toSorted();
    expect(columns).toEqual(["id", "mine"]);

    if (names.includes("migrations")) {
      const rows = db
        .query<{ version: number }, []>("SELECT version FROM migrations")
        .all();
      expect(rows).toEqual([]);
    }
    db.close();
  });
});

describe("src/store/db openDatabase", () => {
  test("creates the file, sets the pragmas, and migrates", async () => {
    const path = await tempDbPath("pragmas.db");
    const db = openDatabase(path, APPLIED_AT);

    expect(existsSync(path)).toBe(true);
    expect(String(pragma(db, "journal_mode")).toLowerCase()).toBe("wal");
    expect(pragma(db, "busy_timeout")).toBe(5000);
    expect(pragma(db, "foreign_keys")).toBe(1);
    expect(pragma(db, "synchronous")).toBe(1);

    expect(tableNames(db)).toContain("items");
    expect(migrate(db, new Date("2026-05-01T00:00:00.000Z"))).toBe(0);
    db.close();
  });

  test("sets the pragmas on a second connection to the same file", async () => {
    // Every pragma but journal_mode is per connection, and the worker opens
    // its own.
    const path = await tempDbPath("second.db");
    const first = openDatabase(path, APPLIED_AT);
    const second = openDatabase(path, APPLIED_AT);

    expect(pragma(second, "busy_timeout")).toBe(5000);
    expect(pragma(second, "foreign_keys")).toBe(1);
    expect(pragma(second, "synchronous")).toBe(1);
    first.close();
    second.close();
  });

  test("opening an existing database applies no migration twice", async () => {
    const path = await tempDbPath("reopen.db");
    const first = openDatabase(path, APPLIED_AT);
    first.close();

    const second = openDatabase(path, new Date("2026-06-01T00:00:00.000Z"));
    const rows = second
      .query<{ version: number; applied_at: string }, []>(
        "SELECT version, applied_at FROM migrations ORDER BY version",
      )
      .all();
    expect(rows).toHaveLength(MIGRATIONS.length);
    expect(rows[0]!.applied_at).toBe("2026-02-01T00:00:00.000Z");
    second.close();
  });

  test("turns foreign keys on, so deleting a user cascades", async () => {
    const path = await tempDbPath("cascade.db");
    const db = openDatabase(path, APPLIED_AT);
    const user = "11111111-1111-4111-8111-111111111111";
    const item = "aaaaaaaa-0000-4000-8000-000000000001";
    db.run(
      "INSERT INTO users (id, subject, email, created_at) VALUES (?, ?, ?, ?)",
      [user, "subject-1", null, "2026-02-01T00:00:00.000Z"],
    );
    db.run(
      "INSERT INTO items (id, user_id, kind, url, title, author, created_at, ingested_at) VALUES (?, ?, 'article', NULL, 'A title', NULL, ?, NULL)",
      [item, user, "2026-02-01T00:00:00.000Z"],
    );
    db.run(
      "INSERT INTO annotations (id, user_id, item_id, start_offset, end_offset, quote, note, created_at, updated_at) VALUES (?, ?, ?, 0, 4, 'quot', NULL, ?, ?)",
      [
        "bbbbbbbb-0000-4000-8000-000000000001",
        user,
        item,
        "2026-02-01T00:00:00.000Z",
        "2026-02-01T00:00:00.000Z",
      ],
    );
    db.run(
      "INSERT INTO api_tokens (id, user_id, name, token_hash, created_at, last_used_at) VALUES (?, ?, 'laptop', ?, ?, NULL)",
      [
        "dddddddd-0000-4000-8000-000000000001",
        user,
        "hash-1",
        "2026-02-01T00:00:00.000Z",
      ],
    );
    db.run(
      "INSERT INTO fetch_requests (id, user_id, item_id, url, source_path, state, lease_expires_at, attempts, error_code, created_at) VALUES (?, ?, NULL, 'https://example.com', NULL, 'queued', NULL, 0, NULL, ?)",
      [
        "cccccccc-0000-4000-8000-000000000001",
        user,
        "2026-02-01T00:00:00.000Z",
      ],
    );

    const count = (table: string): number =>
      db
        .query<{ n: number }, []>(`SELECT COUNT(*) AS n FROM ${table}`)
        .get()!.n;

    expect(count("items")).toBe(1);
    expect(count("annotations")).toBe(1);
    expect(count("api_tokens")).toBe(1);
    expect(count("fetch_requests")).toBe(1);

    db.run("DELETE FROM users WHERE id = ?", [user]);

    expect(count("items")).toBe(0);
    expect(count("annotations")).toBe(0);
    expect(count("api_tokens")).toBe(0);
    expect(count("fetch_requests")).toBe(0);
    db.close();
  });
});

describe("src/store/db tableInfo", () => {
  test("lists every real table with its SQL and columns", () => {
    const db = migratedMemoryDb();
    const tables = tableInfo(db);
    const names = tables.map((table) => table.name);

    for (const name of SCHEMA_TABLES) {
      expect(names).toContain(name);
    }

    for (const table of tables) {
      expect(typeof table.sql).toBe("string");
      expect(table.sql.length).toBeGreaterThan(0);
      expect(Array.isArray(table.columns)).toBe(true);
      expect(table.columns.length).toBeGreaterThan(0);
    }

    // SQLite backs an FTS5 table with five shadow tables. They are real rows
    // of sqlite_master, so tableInfo reports them.
    for (const suffix of FTS_SHADOW_SUFFIXES) {
      expect(names).toContain(`items_fts${suffix}`);
    }
    expect(
      tables.find((table) => table.name === "items_fts")!.sql,
    ).toContain("USING fts5");
    db.close();
  });

  test("reports no index", () => {
    const db = migratedMemoryDb();
    const names = tableInfo(db).map((table) => table.name);
    for (const index of [
      "api_tokens_user",
      "items_user_created",
      "items_user_url",
      "annotations_user_item_offset",
      "fetch_requests_claimable",
    ]) {
      expect(names).not.toContain(index);
    }
    db.close();
  });

  test("holds exactly the seven tables outside the FTS shadow set", () => {
    const db = migratedMemoryDb();
    const shadows = FTS_SHADOW_SUFFIXES.map((suffix) => `items_fts${suffix}`);
    const names = tableInfo(db)
      .map((table) => table.name)
      .filter((name) => !shadows.includes(name))
      .toSorted();
    expect(names).toEqual(SCHEMA_TABLES);
    db.close();
  });
});

describe("test/invariants/lib EXPECTED_COLUMNS", () => {
  // These lists are the specification. Adding, renaming, or dropping a column
  // fails here on purpose, and the constant is the one place to change it.
  test("names the seven tables of version 1", () => {
    expect(Object.keys(EXPECTED_COLUMNS).toSorted()).toEqual(SCHEMA_TABLES);
  });

  test("pins the columns of every table in the schema", () => {
    expect([...EXPECTED_COLUMNS.migrations!]).toEqual(["applied_at", "version"]);
    expect([...EXPECTED_COLUMNS.users!]).toEqual([
      "created_at",
      "email",
      "id",
      "subject",
    ]);
    expect([...EXPECTED_COLUMNS.api_tokens!]).toEqual([
      "created_at",
      "id",
      "last_used_at",
      "name",
      "token_hash",
      "user_id",
    ]);
    expect([...EXPECTED_COLUMNS.items!]).toEqual([
      "author",
      "created_at",
      "id",
      "ingested_at",
      "kind",
      "title",
      "url",
      "user_id",
    ]);
    expect([...EXPECTED_COLUMNS.annotations!]).toEqual([
      "created_at",
      "end_offset",
      "id",
      "item_id",
      "note",
      "quote",
      "start_offset",
      "updated_at",
      "user_id",
    ]);
    expect([...EXPECTED_COLUMNS.fetch_requests!]).toEqual([
      "attempts",
      "created_at",
      "error_code",
      "id",
      "item_id",
      "lease_expires_at",
      "source_path",
      "state",
      "url",
      "user_id",
    ]);
    expect([...EXPECTED_COLUMNS.items_fts!]).toEqual([
      "author",
      "item_id",
      "title",
      "transcript",
      "user_id",
    ]);
  });

  test("matches the migrated database, table for table", () => {
    const db = migratedMemoryDb();
    const tables = tableInfo(db);
    for (const name of SCHEMA_TABLES) {
      expect(columnsOf(tables, name)).toEqual([...EXPECTED_COLUMNS[name]!]);
    }
    db.close();
  });
});

describe("invariant 6: tenancy", () => {
  test("the migrated schema is clean", () => {
    const db = migratedMemoryDb();
    expect(checkTenancy(tableInfo(db))).toEqual([]);
    db.close();
  });

  test("flags a table with no user_id column", () => {
    const violations = checkTenancy([
      fakeTable("notes", ["id", "body", "created_at"]),
    ]);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("notes");
    expect(violations[0]!.rule).toBe("tenancy");
    expect(typeof violations[0]!.detail).toBe("string");
    expect(violations[0]!.detail.length).toBeGreaterThan(0);
  });

  test("flags every offending table, not only the first", () => {
    const violations = checkTenancy([
      fakeTable("notes", ["id", "body"]),
      fakeTable("tags", ["id", "label"]),
      fakeTable("items", ["id", "user_id"]),
    ]);
    expect(violations).toHaveLength(2);
    expect(violations.map((violation) => violation.table).toSorted()).toEqual([
      "notes",
      "tags",
    ]);
  });

  test("exempts migrations and users", () => {
    expect(
      checkTenancy([
        fakeTable("migrations", ["version", "applied_at"]),
        fakeTable("users", ["id", "subject", "email", "created_at"]),
      ]),
    ).toEqual([]);
  });

  test("exempts the five shadow tables of an FTS5 virtual table", () => {
    const tables = [
      fakeFtsTable("items_fts", [
        "title",
        "author",
        "transcript",
        "item_id",
        "user_id",
      ]),
      ...fakeShadowTables("items_fts"),
    ];
    expect(tables).toHaveLength(6);
    expect(checkTenancy(tables)).toEqual([]);
  });

  test("flags items_fts_notes, which only looks like a shadow table", () => {
    // A prefix match would wave this through. The exemption is an exact list
    // of five names, so a table someone adds later still has to carry
    // user_id.
    const tables = [
      fakeFtsTable("items_fts", [
        "title",
        "author",
        "transcript",
        "item_id",
        "user_id",
      ]),
      ...fakeShadowTables("items_fts"),
      fakeTable("items_fts_notes", ["id", "body"]),
    ];
    const violations = checkTenancy(tables);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("items_fts_notes");
  });

  test("exempts a table SQLite owns, such as sqlite_stat1", () => {
    // ANALYZE and PRAGMA optimize create sqlite_stat1, which has no user_id
    // and appears in sqlite_master as an ordinary table.
    const tables = [
      ...schemaTables(),
      ...fakeShadowTables("items_fts"),
      fakeTable("sqlite_stat1", ["tbl", "idx", "stat"]),
      fakeTable("sqlite_sequence", ["name", "seq"]),
    ];
    expect(checkTenancy(tables)).toEqual([]);
  });

  test("ANALYZE on the real database does not break the check", () => {
    const db = migratedMemoryDb();
    db.exec("ANALYZE");
    expect(tableNames(db)).toContain("sqlite_stat1");
    expect(checkTenancy(tableInfo(db))).toEqual([]);
    db.close();
  });

  test("does not exempt the FTS5 table itself", () => {
    const violations = checkTenancy([
      fakeFtsTable("items_fts", ["title", "author", "transcript", "item_id"]),
      ...fakeShadowTables("items_fts"),
    ]);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("items_fts");
  });

  test("does not exempt a shadow name with no FTS5 table behind it", () => {
    // No `USING fts5` declares `notes_fts`, so `notes_fts_data` is a plain
    // table and the rule applies to it.
    const violations = checkTenancy([fakeTable("notes_fts_data", ["id", "block"])]);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("notes_fts_data");
  });
});

describe("invariant 7: no positions in the database", () => {
  test("the migrated schema is clean", () => {
    const db = migratedMemoryDb();
    expect(checkNoPositionsInDb(tableInfo(db))).toEqual([]);
    db.close();
  });

  test("the migrated schema stays clean after ANALYZE", () => {
    const db = migratedMemoryDb();
    db.exec("ANALYZE");
    expect(tableNames(db)).toContain("sqlite_stat1");
    expect(checkNoPositionsInDb(tableInfo(db))).toEqual([]);
    db.close();
  });

  test("accepts the schema built from EXPECTED_COLUMNS", () => {
    const tables = [...schemaTables(), ...fakeShadowTables("items_fts")];
    expect(tables.length).toBeGreaterThan(7);
    expect(checkNoPositionsInDb(tables)).toEqual([]);
  });

  test("flags a column outside the allowlist, whatever it is named", () => {
    // `locator` passes every name rule. Only the allowlist catches it, which
    // is why the allowlist leads.
    const tables = schemaTables().map((table) =>
      table.name === "annotations"
        ? fakeTable("annotations", [...table.columns, "locator"])
        : table,
    );
    const violations = checkNoPositionsInDb(tables);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("annotations");
    expect(violations[0]!.detail).toContain("locator");
  });

  test("flags a missing column too, because the set must match exactly", () => {
    const tables = schemaTables().map((table) =>
      table.name === "items"
        ? fakeTable(
            "items",
            table.columns.filter((column) => column !== "author"),
          )
        : table,
    );
    const violations = checkNoPositionsInDb(tables);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("items");
    expect(violations[0]!.detail).toContain("author");
  });

  test("allows source_path, the one name on the allowlist", () => {
    // fetch_requests carries source_path in EXPECTED_COLUMNS, and the name
    // pass must not flag it either.
    expect(checkNoPositionsInDb(schemaTables())).toEqual([]);
    expect(
      checkNoPositionsInDb([fakeTable("later_table", ["user_id", "source_path"])]),
    ).toEqual([]);
  });

  test("allows transcript offsets", () => {
    expect(
      checkNoPositionsInDb([
        fakeTable("later_table", ["user_id", "start_offset", "end_offset"]),
      ]),
    ).toEqual([]);
  });

  test("the name pass flags a column whose name ends in _path", () => {
    const violations = checkNoPositionsInDb([
      fakeTable("later_table", ["id", "user_id", "node_path"]),
    ]);
    expect(violations).toHaveLength(1);
    expect(violations[0]!.table).toBe("later_table");
    expect(violations[0]!.detail).toContain("node_path");
    expect(violations[0]!.rule).toBe("no-positions-in-db");
  });

  test("the name pass flags xpath, selector, dom, node, and doc_index", () => {
    const violations = checkNoPositionsInDb([
      fakeTable("a", ["xpath"]),
      fakeTable("b", ["css_selector"]),
      fakeTable("c", ["dom_ref"]),
      fakeTable("d", ["node_id"]),
      fakeTable("e", ["doc_index"]),
    ]);
    expect(violations).toHaveLength(5);
    const joined = detailOf(violations);
    for (const column of [
      "xpath",
      "css_selector",
      "dom_ref",
      "node_id",
      "doc_index",
    ]) {
      expect(joined).toContain(column);
    }
  });

  test("flags every offending column of one table", () => {
    const violations = checkNoPositionsInDb([
      fakeTable("later_table", ["id", "node_path", "start_offset", "xpath"]),
    ]);
    expect(violations).toHaveLength(2);
    const joined = detailOf(violations);
    expect(joined).toContain("node_path");
    expect(joined).toContain("xpath");
  });
});
