// Sealed acceptance test for milestone 3. Do not edit this file.
//
// What the implementer must create
// --------------------------------
// 1. `src/core/sanitize.ts`, exporting `sanitize(html: string): string`.
// 2. `src/core/walk.ts`, exporting `walk(html, options?): Transcript` and the
//    `BLOCK_ELEMENTS` array.
// 3. `WALK_UNPARSEABLE` added to `ERROR_CODES` in `src/contracts/errors.ts`.
//
// The specification is `plan/briefs/03-walk-spec.md`, revision 2. This file is
// that specification as assertions. Where the two disagree, this file wins.
//
// Facts verified against the real packages before this file was written
// ---------------------------------------------------------------------
// Every expectation below was checked against jsdom 30.0.1, dompurify 3.4.13,
// and @mozilla/readability 0.6.0, not reasoned about.
//
// - jsdom drops the single newline right after a `<pre>` start tag, so the
//   first preserved line of `pre.html` is `    def greet(name):`.
// - jsdom inserts the implied `tbody`, so `table.html` has one `tbody` child.
// - DOMPurify with the allow-list config drops every hostile construct in
//   `hostile.html` and keeps `href="#fragment"` and `src="pictures/dot.png"`.
// - Readability keeps only the `<article>` subtree of `boilerplate.html` and
//   excludes the nav, header, aside, and footer.
// - `sanitize(sanitize(html)) === sanitize(html)` for all ten fixtures.
//
// The two new fixtures are part of the specification
// --------------------------------------------------
// `test/fixtures/synthetic/boilerplate.html` and
// `test/fixtures/synthetic/hostile.html` were written with this file and
// verified against the libraries. Do not edit them. Editing a fixture to make
// an assertion pass defeats the assertion.
//
// Node paths are resolved, never hardcoded
// ----------------------------------------
// A `node_path` is a slash-separated list of child indices counted from
// `document.documentElement`, over all child nodes including text nodes. The
// index of `body` differs between documents, because DOMPurify's output may
// hold a text node between `</head>` and `<body>`. So this file resolves every
// path against the sanitized document rather than writing one down.
//
// `startOffset` and `validateMap`
// -------------------------------
// `walk` returns runs already based at `startOffset`. When `startOffset` is
// greater than 0 the runs do not start at 0, so `validateMap(map, text.length)`
// is the wrong check and this file tiles by hand instead.

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { JSDOM } from "jsdom";

import { AppError, ERROR_CODES } from "../../src/contracts/errors";
import type { Run, Transcript } from "../../src/contracts/transcript";
import { validateMap } from "../../src/contracts/transcript";
import { sanitize } from "../../src/core/sanitize";
import { BLOCK_ELEMENTS, walk } from "../../src/core/walk";

const repoRoot = join(import.meta.dir, "..", "..");
const syntheticDir = join(repoRoot, "test", "fixtures", "synthetic");

function fixture(name: string): string {
  return readFileSync(join(syntheticDir, `${name}.html`), "utf8");
}

function caught(run: () => unknown): unknown {
  try {
    run();
  } catch (error) {
    return error;
  }
  throw new Error("expected the call to throw");
}

function transcriptOf(name: string): Transcript {
  return walk(sanitize(fixture(name)));
}

function documentOf(html: string): Document {
  return new JSDOM(html).window.document;
}

function resolvePath(doc: Document, path: string): Node | null {
  let node: Node = doc.documentElement;
  if (path === "") return node;
  for (const part of path.split("/")) {
    const index = Number(part);
    const next: Node | undefined = node.childNodes[index];
    if (!next) return null;
    node = next;
  }
  return node;
}

function ancestorTags(doc: Document, path: string): string[] {
  const tags: string[] = [];
  let node: Node | null = resolvePath(doc, path);
  while (node) {
    if (node.nodeType === 1) tags.push((node as Element).tagName.toLowerCase());
    node = node.parentNode;
  }
  return tags;
}

function blocksOf(map: { runs: Run[] }): Map<number, Run[]> {
  const blocks = new Map<number, Run[]>();
  for (const run of map.runs) {
    const found = blocks.get(run.block_index);
    if (found) found.push(run);
    else blocks.set(run.block_index, [run]);
  }
  return blocks;
}

// The exact transcript of every fixture, worked out by hand from the
// specification and the fixture sources before any implementation existed.
// `\n` is a real newline. No transcript starts or ends with one.
const EXPECTED: Record<string, string> = {
  blocks: [
    "First heading",
    "First paragraph with several words in it.",
    "Second paragraph follows the first with one newline between blocks.",
    "A quoted block sits between paragraphs.",
  ].join("\n"),

  // `emphasisbold` runs together because no whitespace separates `</em>` from
  // `<strong>`. `linkcode.` runs together for the same reason. The one space
  // before `link` is the collapsed newline and indent after `</strong>`.
  inline: [
    "Inline elements with no separator: emphasisbold linkcode.",
    "Nested inline too: outer inner outer tail.",
  ].join("\n"),

  // Three blocks, not five. Each `br` newline belongs to its paragraph's
  // block, and the `hr` emits nothing and takes no index. There is one space
  // after `nothing:`, not two: the image emits nothing and the whitespace on
  // either side of it collapses across the inline boundary.
  void: [
    "Line one\nLine two\nLine three.",
    "An image emits nothing: and text resumes.",
    "A paragraph after a horizontal rule.",
  ].join("\n"),

  // ` ` is the no-break space from `&nbsp;`. It is not ASCII whitespace,
  // so it never collapses, and the ASCII space on either side of it does.
  entities: [
    "Ampersand & and less-than < here.",
    "Apostrophe ' and a named entity: \u00a9 \u00a0 \u2014 end.",
  ].join("\n"),

  astral: [
    "Astral characters take two UTF-16 code units: \u{1f600} \u{1f680} \u{1d49c}.",
    "Math and music planes too: \u{1d54f} \u{1d11e}. Mixed with BMP text: a\u{1f600}b\u{1f680}c.",
  ].join("\n"),

  // The parser drops the newline right after `<pre>`, so the first preserved
  // line is the indented `def`. The line holding four spaces is the last line
  // of the `pre`, preserved from the source. The three spaces inside
  // `hello   {name}` survive too. This is the one fixture whose transcript
  // holds runs of whitespace.
  pre: [
    "Preformatted",
    '    def greet(name):\n        print(f"hello   {name}")\n          return 0\n    ',
    "The paragraph before and after collapses whitespace.",
  ].join("\n"),

  // Eight blocks. Each `th` and `td` is its own block, and row structure does
  // not survive into the transcript.
  table: [
    "Prices",
    "Name",
    "Price",
    "Tea",
    "3.50",
    "Coffee",
    "4.00",
    "A table caption after the grid.",
  ].join("\n"),

  // `bdi` is inline and emits nothing of its own. No bidirectional control
  // characters enter the transcript.
  rtl: [
    "هذا نص من اليمين إلى اليسار.",
    "Left-to-right sentence then نص عربي then more.",
    "Mixed bidirectional: مرحبا world مرحبا.",
  ].join("\n"),

  // Twelve blocks. `header`, `article`, `aside`, `ul`, and `footer` emit no
  // text of their own, so none of them takes an index.
  boilerplate: [
    "Home Archive About",
    "The Weekly Ledger",
    "A newsletter about small systems.",
    "How a transcript keeps its shape",
    "A transcript is the full text of an item as one ordered stream of characters, written in reading order. Every feature in this system anchors to a position in that stream, which is why the stream must never be rebuilt differently from one run to the next.",
    "The map records which sanitized node produced each span of transcript characters. Search hits, annotations, and rendered pages are all projections through that map. Nothing else stores a position, so nothing else can disagree with it.",
    "Keeping one source of truth costs an extra parse at ingest time. That is a small price for a guarantee that a highlight saved today still points at the same words a year from now, even after the renderer changes.",
    "The alternative is to store a position in each feature that needs one. Every such copy is a chance to drift, and drift in an annotation offset is silent. The reader sees a highlight over the wrong sentence and has no way to tell that the text moved rather than the highlight.",
    "Related",
    "An earlier note on offsets",
    "Why the map is not a database table",
    "Copyright 2026 The Weekly Ledger. All rights reserved.",
  ].join("\n"),

  // Four blocks, and the middle one is the body's own. The three links sit
  // directly in the body, so they belong to the body's block. The body opens a
  // new block each time a child block has taken an index since its last text,
  // which is why the links are block 1 and `A ping link.` is block 3.
  hostile: [
    "Attributes are dropped and this text stays.",
    "A scheme link is stripped. A tab-obfuscated scheme link. A fragment link survives.",
    "Form text survives the unwrap.",
    "A ping link.",
  ].join("\n"),
};

const FIXTURES = Object.keys(EXPECTED);

const EXPECTED_BLOCK_COUNT: Record<string, number> = {
  blocks: 4,
  inline: 2,
  void: 3,
  entities: 2,
  astral: 2,
  pre: 3,
  table: 8,
  rtl: 3,
  boilerplate: 12,
  hostile: 4,
};

describe("the error code exists", () => {
  test("WALK_UNPARSEABLE is a known code", () => {
    expect(ERROR_CODES).toContain("WALK_UNPARSEABLE");
  });
});

describe("sanitize", () => {
  test("returns a document that starts with a doctype", () => {
    const clean = sanitize(fixture("blocks"));
    expect(clean.startsWith("<!DOCTYPE html>")).toBe(true);
  });

  test("keeps the head and the title", () => {
    const doc = documentOf(sanitize(fixture("blocks")));
    expect(doc.title).toBe("blocks");
  });

  test("is stable, which is the mutation-XSS guard", () => {
    for (const name of FIXTURES) {
      const once = sanitize(fixture(name));
      expect(sanitize(once)).toBe(once);
    }
  });

  test("throws WALK_UNPARSEABLE for a non-string input", () => {
    const error = caught(() => sanitize(undefined as unknown as string));
    expect(error).toBeInstanceOf(AppError);
    expect((error as AppError).code).toBe("WALK_UNPARSEABLE");
  });

  test("throws WALK_UNPARSEABLE for whitespace-only input", () => {
    const error = caught(() => sanitize("   \n\t  "));
    expect(error).toBeInstanceOf(AppError);
    expect((error as AppError).code).toBe("WALK_UNPARSEABLE");
  });

  describe("the allow-list drops every hostile construct", () => {
    const clean = sanitize(fixture("hostile"));
    const lower = clean.toLowerCase();

    // Each of these is one row of the table in the specification.
    const forbidden: Array<[string, string]> = [
      ["a script element", "<script"],
      ["a style element", "<style"],
      ["an iframe", "<iframe"],
      ["an object", "<object"],
      ["an embed", "<embed"],
      ["a base element", "<base"],
      ["a meta refresh", "<meta"],
      ["a stylesheet link", "<link"],
      ["an svg element", "<svg"],
      ["a math element", "<math"],
      ["a form element", "<form"],
      ["an input element", "<input"],
      ["a video element", "<video"],
      ["an event handler attribute", "onclick"],
      ["a style attribute", "style="],
      ["a srcset attribute", "srcset"],
      ["a ping attribute", "ping="],
      ["a poster attribute", "poster"],
      ["a background attribute", "background"],
      ["a data attribute", "data-x"],
      ["a javascript scheme", "javascript"],
      ["the hostile host", "evil.example"],
      ["the tracker host", "tracker.example"],
    ];

    for (const [what, needle] of forbidden) {
      test(`drops ${what}`, () => {
        expect(lower).not.toContain(needle);
      });
    }

    test("keeps a fragment link, which relative URLs need", () => {
      expect(clean).toContain('href="#fragment"');
    });

    test("keeps a relative image source", () => {
      expect(clean).toContain('src="pictures/dot.png"');
    });

    test("unwraps a form and keeps the paragraph inside it", () => {
      expect(clean).toContain("Form text survives the unwrap.");
    });

    test("keeps noscript content, which is the real image in an archive", () => {
      expect(clean).toContain("pictures/lazy.png");
    });

    test("keeps the text of an element whose href it dropped", () => {
      expect(clean).toContain("A scheme link is stripped.");
    });
  });
});

describe("walk produces the exact transcript of every fixture", () => {
  for (const name of FIXTURES) {
    test(name, () => {
      expect(transcriptOf(name).text).toBe(EXPECTED[name]!);
    });
  }
});

describe("walk produces a well-formed map for every fixture", () => {
  for (const name of FIXTURES) {
    describe(name, () => {
      const t = transcriptOf(name);
      const doc = documentOf(sanitize(fixture(name)));

      test("the map tiles the transcript", () => {
        expect(() => validateMap(t.map, t.text.length)).not.toThrow();
      });

      test("concatenating the runs rebuilds the transcript", () => {
        const joined = t.map.runs
          .map((run) => t.text.slice(run.start, run.end))
          .join("");
        expect(joined).toBe(t.text);
      });

      test("doc_index is 0 for a web article", () => {
        for (const run of t.map.runs) expect(run.doc_index).toBe(0);
      });

      test("block_index starts at 0 and skips no value", () => {
        const seen = [...blocksOf(t.map).keys()];
        expect(seen).toEqual(seen.map((_, i) => i));
      });

      test("the block count is the one the specification names", () => {
        expect(blocksOf(t.map).size).toBe(EXPECTED_BLOCK_COUNT[name]!);
      });

      test("runs sharing a block_index are contiguous", () => {
        for (const runs of blocksOf(t.map).values()) {
          for (let i = 1; i < runs.length; i += 1) {
            expect(runs[i]!.start).toBe(runs[i - 1]!.end);
          }
        }
      });

      test("is_content is uniform within a block", () => {
        for (const runs of blocksOf(t.map).values()) {
          const first = runs[0]!.is_content;
          for (const run of runs) expect(run.is_content).toBe(first);
        }
      });

      test("every node_path is a list of non-negative integers", () => {
        for (const run of t.map.runs) {
          expect(run.node_path).toMatch(/^\d+(\/\d+)*$/);
        }
      });

      test("every node_path resolves in the sanitized document", () => {
        for (const run of t.map.runs) {
          expect(resolvePath(doc, run.node_path)).not.toBeNull();
        }
      });

      test("every run sits inside the body, never the head", () => {
        for (const run of t.map.runs) {
          expect(ancestorTags(doc, run.node_path)).toContain("body");
        }
      });

      test("no run boundary splits a surrogate pair", () => {
        for (const run of t.map.runs) {
          for (const at of [run.start, run.end]) {
            if (at === 0 || at === t.text.length) continue;
            const before = t.text.charCodeAt(at - 1);
            expect(before >= 0xd800 && before <= 0xdbff).toBe(false);
          }
        }
      });

      test("the transcript neither starts nor ends with a newline", () => {
        expect(t.text.startsWith("\n")).toBe(false);
        expect(t.text.endsWith("\n")).toBe(false);
      });
    });
  }
});

describe("the head never reaches the transcript", () => {
  test("the title is metadata, not text", () => {
    const clean = sanitize(
      "<html><head><title>Zarfblat</title></head><body><p>body text</p></body></html>",
    );
    expect(clean).toContain("Zarfblat");
    expect(walk(clean).text).toBe("body text");
  });
});

describe("separators", () => {
  test("a block's range starts at its first character, never one before", () => {
    // Milestone 9 turns a reader selection into an offset. A separator that
    // led a block instead of trailing the previous one would make every
    // whole-paragraph highlight store an offset one too low.
    const t = transcriptOf("blocks");
    const second = blocksOf(t.map).get(1)!;
    expect(t.text.slice(second[0]!.start, second[second.length - 1]!.end))
      .toBe("First paragraph with several words in it.\n");
    expect(t.text[second[0]!.start]).toBe("F");
  });

  test("a separator carries the previous block's path and flag", () => {
    const t = transcriptOf("blocks");
    const first = blocksOf(t.map).get(0)!;
    const last = first[first.length - 1]!;
    expect(t.text.slice(last.start, last.end).endsWith("\n")).toBe(true);
    expect(last.block_index).toBe(0);
  });

  test("a pre block that ends with a newline swallows the next separator", () => {
    const t = walk(sanitize("<html><body><pre>x\n</pre><p>y</p></body></html>"));
    expect(t.text).toBe("x\ny");
  });

  test("two breaks in a row yield two newlines", () => {
    const t = walk(sanitize("<html><body><p>a<br><br>b</p></body></html>"));
    expect(t.text).toBe("a\n\nb");
  });

  test("a break's newline suppresses the separator that would follow it", () => {
    const t = walk(sanitize("<html><body><p>a<br></p><p>b</p></body></html>"));
    expect(t.text).toBe("a\nb");
  });

  test("a break's run carries the break element's own path", () => {
    const clean = sanitize("<html><body><p>a<br>b</p></body></html>");
    const t = walk(clean);
    const doc = documentOf(clean);
    const breakRun = t.map.runs.find(
      (run) => t.text.slice(run.start, run.end) === "\n",
    )!;
    const node = resolvePath(doc, breakRun.node_path) as Element;
    expect(node.nodeType).toBe(1);
    expect(node.tagName.toLowerCase()).toBe("br");
  });

  test("a break takes no block index of its own", () => {
    const t = walk(sanitize("<html><body><p>a<br>b</p></body></html>"));
    expect(blocksOf(t.map).size).toBe(1);
  });

  test("an empty block takes no index and leaves no hole", () => {
    const t = walk(
      sanitize("<html><body><p>a</p><p></p><p>  </p><p>b</p></body></html>"),
    );
    expect(t.text).toBe("a\nb");
    expect(blocksOf(t.map).size).toBe(2);
  });

  test("a block reopens after a nested block has taken an index", () => {
    // `lead` is 0, `inner` is 1, `tail` is 2. Reusing 0 for `tail` would make
    // block_index decrease, which validateMap rejects.
    const t = walk(
      sanitize(
        "<html><body><blockquote>lead <p>inner</p> tail</blockquote></body></html>",
      ),
    );
    expect(t.text).toBe("lead\ninner\ntail");
    const blocks = blocksOf(t.map);
    expect(blocks.size).toBe(3);
    expect(t.text.slice(blocks.get(2)![0]!.start)).toBe("tail");
  });

  test("text directly in the body belongs to the body's block", () => {
    const t = walk(sanitize("<html><body>loose text</body></html>"));
    expect(t.text).toBe("loose text");
    expect(blocksOf(t.map).size).toBe(1);
  });
});

describe("whitespace", () => {
  test("collapses across an inline boundary, not inside one text node", () => {
    const t = walk(
      sanitize('<html><body><p>a <img src="d.png" alt="d"> b</p></body></html>'),
    );
    expect(t.text).toBe("a b");
  });

  test("a block never begins or ends with a space", () => {
    const t = walk(sanitize("<html><body><p>   a   </p></body></html>"));
    expect(t.text).toBe("a");
  });

  test("emits no zero-length run for a text node that collapses away", () => {
    const t = walk(sanitize("<html><body><p> <em>x</em></p></body></html>"));
    expect(t.text).toBe("x");
    for (const run of t.map.runs) expect(run.end).toBeGreaterThan(run.start);
  });

  test("a tab and a newline collapse to one space", () => {
    const t = walk(sanitize("<html><body><p>a \t\n b</p></body></html>"));
    expect(t.text).toBe("a b");
  });

  test("a no-break space never collapses", () => {
    const t = walk(sanitize("<html><body><p>a \u00a0 b</p></body></html>"));
    expect(t.text).toBe("a \u00a0 b");
  });

  test("pre preserves whitespace and its own edges", () => {
    const t = walk(sanitize("<html><body><pre>  a  \n  b  </pre></body></html>"));
    expect(t.text).toBe("  a  \n  b  ");
  });

  test("pre may hold two newlines in a row", () => {
    const t = walk(sanitize("<html><body><pre>a\n\nb</pre></body></html>"));
    expect(t.text).toBe("a\n\nb");
  });
});

describe("content flags", () => {
  const clean = sanitize(fixture("boilerplate"));
  const t = walk(clean);
  const doc = documentOf(clean);

  test("the article's runs are content", () => {
    const inArticle = t.map.runs.filter((run) =>
      ancestorTags(doc, run.node_path).includes("article"),
    );
    expect(inArticle.length).toBeGreaterThan(0);
    for (const run of inArticle) expect(run.is_content).toBe(true);
  });

  for (const tag of ["nav", "header", "aside", "footer"]) {
    test(`the ${tag}'s runs are not content`, () => {
      const inside = t.map.runs.filter((run) => {
        const tags = ancestorTags(doc, run.node_path);
        return tags.includes(tag) && !tags.includes("article");
      });
      expect(inside.length).toBeGreaterThan(0);
      for (const run of inside) expect(run.is_content).toBe(false);
    });
  }

  test("every run is content when readability declines to score", () => {
    // A short document readability will not score is still a document the
    // reader must be able to read. This is the rule, not a fallback.
    const t2 = walk(sanitize("<html><body><p>Too short to score.</p></body></html>"));
    expect(t2.map.runs.length).toBeGreaterThan(0);
    for (const run of t2.map.runs) expect(run.is_content).toBe(true);
  });

  test("the walk never writes its private stamp into the document", () => {
    expect(sanitize(fixture("boilerplate"))).not.toContain("data-cp-path");
    walk(clean);
    expect(clean).not.toContain("data-cp-path");
  });
});

describe("block elements", () => {
  test("BLOCK_ELEMENTS is the explicit list the specification names", () => {
    expect([...BLOCK_ELEMENTS].sort()).toEqual(
      [
        "address", "article", "aside", "blockquote", "caption", "dd",
        "details", "div", "dl", "dt", "fieldset", "figcaption", "figure",
        "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup",
        "hr", "li", "main", "nav", "ol", "p", "pre", "section", "summary",
        "table", "tbody", "td", "tfoot", "th", "thead", "tr", "ul",
      ].sort(),
    );
  });

  test("body is not on the list, so it emits no separator of its own", () => {
    expect(BLOCK_ELEMENTS).not.toContain("body");
  });
});

describe("options", () => {
  test("all three default to 0", () => {
    const t = transcriptOf("blocks");
    expect(t.map.runs[0]!.start).toBe(0);
    expect(t.map.runs[0]!.block_index).toBe(0);
    expect(t.map.runs[0]!.doc_index).toBe(0);
  });

  test("docIndex reaches every run", () => {
    const t = walk(sanitize(fixture("blocks")), { docIndex: 3 });
    for (const run of t.map.runs) expect(run.doc_index).toBe(3);
  });

  test("startOffset bases the runs and prepends one separator", () => {
    const plain = transcriptOf("blocks");
    const shifted = walk(sanitize(fixture("blocks")), { startOffset: 100 });
    expect(shifted.text).toBe(`\n${plain.text}`);
    expect(shifted.map.runs[0]!.start).toBe(100);
    const last = shifted.map.runs[shifted.map.runs.length - 1]!;
    expect(last.end).toBe(100 + shifted.text.length);
  });

  test("the runs still tile when startOffset is not 0", () => {
    const shifted = walk(sanitize(fixture("blocks")), { startOffset: 100 });
    let cursor = 100;
    for (const run of shifted.map.runs) {
      expect(run.start).toBe(cursor);
      expect(run.end).toBeGreaterThan(run.start);
      cursor = run.end;
    }
    expect(cursor).toBe(100 + shifted.text.length);
  });

  test("startBlockIndex numbers the blocks from there", () => {
    const t = walk(sanitize(fixture("blocks")), { startBlockIndex: 7 });
    const seen = [...blocksOf(t.map).keys()];
    expect(seen).toEqual([7, 8, 9, 10]);
  });

  test("startOffset 0 prepends nothing", () => {
    const t = walk(sanitize(fixture("blocks")), { startOffset: 0 });
    expect(t.text.startsWith("\n")).toBe(false);
  });

  test("an empty body yields an empty transcript and no runs", () => {
    const t = walk(sanitize("<html><body></body></html>"));
    expect(t.text).toBe("");
    expect(t.map.runs).toEqual([]);
    expect(() => validateMap(t.map, 0)).not.toThrow();
  });
});

describe("the property test", () => {
  // A small grammar with a fixed seed list, so a failure reproduces. The
  // generator lives here rather than in the implementation's own tests,
  // because a generator the implementer owns is a generator the implementer
  // can narrow.
  function makeRandom(seed: number): () => number {
    let state = seed >>> 0;
    return () => {
      state = (state * 1664525 + 1013904223) >>> 0;
      return state / 0x100000000;
    };
  }

  const WORDS = [
    "alpha", "beta", "gamma", "\u{1f600}", "\u{1d49c}x", "a b", "&amp;",
    "<", "one two", "three",
  ];

  function text(rand: () => number): string {
    const pick = (list: string[]) => list[Math.floor(rand() * list.length)]!;
    const shapes = [
      () => pick(WORDS),
      () => `  ${pick(WORDS)}   ${pick(WORDS)}  `,
      () => "   ",
      () => `${pick(WORDS)}\n\t ${pick(WORDS)}`,
    ];
    return pick(shapes.map((make) => make()));
  }

  function inline(rand: () => number, depth: number): string {
    const choices = [
      () => text(rand),
      () => `<em>${inline(rand, depth + 1)}</em>`,
      () => `<strong>${inline(rand, depth + 1)}</strong>`,
      () => `<a href="/x">${inline(rand, depth + 1)}</a>`,
      () => "<br>",
      () => "<br><br>",
      () => '<img src="d.png" alt="d">',
    ];
    if (depth > 2) return text(rand);
    return choices[Math.floor(rand() * choices.length)]!();
  }

  function block(rand: () => number, depth: number): string {
    const tag = ["p", "div", "blockquote", "section", "li", "h2"][
      Math.floor(rand() * 6)
    ]!;
    if (depth > 2) return `<${tag}>${inline(rand, 0)}</${tag}>`;
    const parts = [inline(rand, 0)];
    const count = Math.floor(rand() * 3);
    for (let i = 0; i < count; i += 1) {
      parts.push(block(rand, depth + 1));
      parts.push(inline(rand, 0));
    }
    return `<${tag}>${parts.join("")}</${tag}>`;
  }

  function makeDocument(seed: number): string {
    const rand = makeRandom(seed);
    const parts: string[] = [];
    const count = 2 + Math.floor(rand() * 5);
    for (let i = 0; i < count; i += 1) {
      parts.push(rand() < 0.2 ? `<pre>  a\n\n  b  </pre>` : block(rand, 0));
      if (rand() < 0.2) parts.push(text(rand));
    }
    return `<!DOCTYPE html><html><head><title>t</title></head><body>${parts.join("")}</body></html>`;
  }

  const SEEDS = [
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584,
    4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393,
  ];

  for (const seed of SEEDS) {
    describe(`seed ${seed}`, () => {
      const html = makeDocument(seed);
      const clean = sanitize(html);
      const t = walk(clean);
      const doc = documentOf(clean);
      const preRuns = new Set<Run>();
      for (const run of t.map.runs) {
        const tags = ancestorTags(doc, run.node_path);
        if (tags.includes("pre") || tags[0] === "br") preRuns.add(run);
      }

      test("sanitize is stable", () => {
        expect(sanitize(clean)).toBe(clean);
      });

      test("the map tiles the transcript", () => {
        expect(() => validateMap(t.map, t.text.length)).not.toThrow();
      });

      test("concatenating the runs rebuilds the transcript", () => {
        const joined = t.map.runs
          .map((run) => t.text.slice(run.start, run.end))
          .join("");
        expect(joined).toBe(t.text);
      });

      test("the transcript neither starts nor ends with a newline", () => {
        expect(t.text.startsWith("\n")).toBe(false);
        expect(t.text.endsWith("\n")).toBe(false);
      });

      test("a doubled newline lies only inside a pre or a break", () => {
        for (let i = 0; i + 1 < t.text.length; i += 1) {
          if (t.text[i] !== "\n" || t.text[i + 1] !== "\n") continue;
          const owner = t.map.runs.find(
            (run) => run.start <= i + 1 && i + 1 < run.end,
          )!;
          expect(preRuns.has(owner)).toBe(true);
        }
      });

      test("block_index starts at 0, never decreases, and skips no value", () => {
        const seen = [...blocksOf(t.map).keys()];
        expect(seen).toEqual(seen.map((_, i) => i));
      });

      test("runs sharing a block_index are contiguous", () => {
        for (const runs of blocksOf(t.map).values()) {
          for (let i = 1; i < runs.length; i += 1) {
            expect(runs[i]!.start).toBe(runs[i - 1]!.end);
          }
        }
      });

      test("every node_path is a list of non-negative integers", () => {
        for (const run of t.map.runs) {
          expect(run.node_path).toMatch(/^\d+(\/\d+)*$/);
        }
      });

      test("every node_path resolves in the sanitized document", () => {
        for (const run of t.map.runs) {
          expect(resolvePath(doc, run.node_path)).not.toBeNull();
        }
      });

      test("no run boundary splits a surrogate pair", () => {
        for (const run of t.map.runs) {
          for (const at of [run.start, run.end]) {
            if (at === 0 || at === t.text.length) continue;
            const before = t.text.charCodeAt(at - 1);
            expect(before >= 0xd800 && before <= 0xdbff).toBe(false);
          }
        }
      });
    });
  }
});
